import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by `flutterfire configure` (project: twsyl-db653).
/// Web values are live. Android/iOS values must be filled by running
/// `flutterfire configure` after registering the app in Firebase Console:
///   Firebase Console > Project settings > Your apps > Add app (Android/iOS)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoBgEXIsYLz6Ke94M7yrE8_jjjPNlGs8',
    appId: '1:303301506528:web:09439d9d1161bd5f9aa785',
    messagingSenderId: '303301506528',
    projectId: 'twsil-db653',
    authDomain: 'twsil-db653.firebaseapp.com',
    storageBucket: 'twsil-db653.firebasestorage.app',
  );
  // TODO(owner): run `flutterfire configure` in mobile/ to fill real values,
  // then add google-services.json (Android) / GoogleService-Info.plist (iOS).

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM20bBSyxrKI4j8ZwAQACm0nDkPkvzLqE',
    appId: '1:303301506528:android:10076f8e2b0c71539aa785',
    messagingSenderId: '303301506528',
    projectId: 'twsil-db653',
    storageBucket: 'twsil-db653.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdoBgEXIsYLz6Ke94M7yrE8_jjjPNlGs8',
    appId: '1:303301506528:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '303301506528',
    projectId: 'twsil-db653',
    storageBucket: 'twsil-db653.firebasestorage.app',
    iosBundleId: 'com.twsil.app',
  );
}
